"use client";
import { useMemo, useState } from "react";
import archive from "../../../public/data/archive-developments.json";
import { SiteHeader } from "../../site-header";

const publicBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
export function RecordsLab() {
  const [playerId,setPlayerId]=useState(archive.similarityPlayers[0]?.playerId ?? "");
  const [mode,setMode]=useState<"batting"|"bowling"|"allround">("allround");
  const selected=archive.similarityPlayers.find((player)=>player.playerId===playerId)!;
  const similar=useMemo(()=>archive.similarityPlayers.filter((player)=>player.playerId!==playerId).map((player)=>({player,distance:mode==="batting"?Math.abs(player.runsPerAppearance-selected.runsPerAppearance):mode==="bowling"?Math.abs(player.wicketsPerAppearance-selected.wicketsPerAppearance):Math.hypot(player.runsPerAppearance-selected.runsPerAppearance,(player.wicketsPerAppearance-selected.wicketsPerAppearance)*20)})).sort((a,b)=>a.distance-b.distance).slice(0,8),[mode,playerId,selected]);
  const latestCoverage=Object.entries(archive.coverage.seasons).at(-1)!;
  return <main className="vault-app records-lab-app"><SiteHeader active="insights"/><section className="archive-summary-hero"><p className="eyebrow">Insights · Advanced records</p><h1>Records laboratory</h1><p>Personal bests, record progression, scorecard coverage and statistically similar active players.</p></section><section className="archive-summary-shell records-lab-grid"><section><h2>Player similarity</h2><div className="lab-controls"><select value={playerId} onChange={(event)=>setPlayerId(event.target.value)}>{archive.similarityPlayers.map((player)=><option value={player.playerId} key={player.playerId}>{player.name}</option>)}</select><select value={mode} onChange={(event)=>setMode(event.target.value as typeof mode)}><option value="batting">Batting</option><option value="bowling">Bowling</option><option value="allround">All-round</option></select></div>{similar.map(({player})=><a href={`${publicBasePath}/players/${player.playerId}/`} key={player.playerId}><span>{player.name}</span><small>{player.runsPerAppearance} runs/app · {player.wicketsPerAppearance} wickets/app</small></a>)}</section><section><h2>Personal bests</h2><h3>Batting strike rate · 20+ balls</h3>{archive.personalBests.battingStrikeRate.slice(0,3).map((row)=><a href={`${publicBasePath}/matches/${row.fixtureId}/`} key={row.fixtureId+row.player}><span>{row.player}</span><small>{row.runs} runs · SR {row.strikeRate}</small></a>)}<h3>Bowling economy · 3+ overs</h3>{archive.personalBests.bowlingEconomy.slice(0,3).map((row)=><a href={`${publicBasePath}/matches/${row.fixtureId}/`} key={row.fixtureId+row.player}><span>{row.player}</span><small>{row.wickets}/{row.runs} · Econ {row.economy}</small></a>)}<h3>Bowling strike rate · 2+ wickets</h3>{archive.personalBests.bowlingStrikeRate.slice(0,3).map((row)=><a href={`${publicBasePath}/matches/${row.fixtureId}/`} key={row.fixtureId+row.player}><span>{row.player}</span><small>{row.wickets}/{row.runs} · SR {row.strikeRate}</small></a>)}</section><section><h2>Record progression</h2>{archive.recordProgression.highestScore.slice(-6).reverse().map((row)=><a href={`${publicBasePath}/matches/${row.fixtureId}/`} key={row.fixtureId}><span>{row.player}</span><small>{row.runs}{row.notOut?"*":""} · {row.date}</small></a>)}</section><section><h2>Data coverage</h2><p>{latestCoverage[0]} contains {latestCoverage[1].battingBallsAvailable} innings with balls faced from {latestCoverage[1].battingInnings} recorded innings, and {latestCoverage[1].bowlingBallsAvailable} complete bowling spells from {latestCoverage[1].bowlingSpells}.</p><small>{archive.coverage.note}</small></section></section></main>;
}
